$ANSIBLE_VAULT;1.1;AES256
39356138353037656665653930356630393164376131623834646438363062313434363130626434
3964326262623530623065653231376637616135656532310a363736326632313431666231383931
65356431623931373633326630666562626637373637383462333631326133373237613464643061
3462313363316366610a313561643963343633356334313131386332383239653862386534316566
63633965663263393132326232366464343539383030396165363431663636663732376363663666
62343036623362366139613761363765626134643039353432313864613733356561333531336364
31366663633835343132343039636262636364383266303365333338323761306163666538316637
66386364613763386134346336643634366131326138623437393535626335643963636562643464
30646135306530616131643465346364313565343734313562653339643464623430373566656232
38323232653930656339643238313262643532396463653332346434323165656466643735663135
34616639363030356635313639303562326465386138366231333161393131366131373331356363
63613835643430333762633733363736366438363966643237646264356231613366333064356463
36373630346437633561396137333961363037373664616634383363633038626330373364346534
39653035323965613135376537623363386663313834376338666133353066333133346434633536
36623763643931613266323063316362363936323637396436386364663334396165656530313565
30326239643933633761
