$ANSIBLE_VAULT;1.1;AES256
61653232653261613532656661616533613363323033663330343931613739623837313030303635
6566353638663730333739333062353537613866396634320a663133613966393838613231353364
37396439616465373465313232326662613433336463623963386466346433643338636136373830
6265336164623835620a626232323534306465356635346431623061313635356162393231333634
64623436663761343966393538303933656564313936343637376264643137633034633430326362
30643964313937376638376430636465323961333062613736373330623434363730353866336431
61356364323133316634363737663666313037313866363362666161643137356532643431623536
39643961353965323835323166393135313534313235346437636338663566386364303264633336
31386436323638376530313764396531383635303136653631346530353265383436366164623532
31353430623033363635333962653132616463636235376361373332326636626662623865336566
63306230663932313132323636353733373838323266643435393264626630663737363361386335
63326165616564643665336131353261356261656563616530323032313037393238366435656566
65623030326265356435613533333262396135653634616330333631613736366536613264636231
31396361613931383065313332333333626464353034666634336162336136633830306364656332
37666466626535626438613030643432353536396336646461383730336433323838346334666231
31616531346334373332
