version: "3.8"

# Start theses services for local development

services:
  postgres:
    build:
      context: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - postgres_network
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "log_line_prefix=%m [%p] %u@%d"
      - "-c"
      - "logging_collector=off" # Logs go to stdout

networks:
  # This network is shared with the migrations service
  # Create if not exists: docker network create postgres_network
  postgres_network:
    external: true
