version: "3.8"

services:
  admin-rover:
    build:
      context: ./apollo/admin-api
      dockerfile: Dockerfile.rover
    working_dir: /workspace
    environment:
      - APOLLO_ELV2_LICENSE=accept
    volumes:
      - ./apollo/admin-api:/workspace
    command: >
      supergraph compose --config supergraph.yaml
      --output supergraph.graphql

  admin-apollo-router:
    build:
      context: ./apollo/admin-api
      dockerfile: Dockerfile.router
    depends_on:
      - admin-rover
    ports:
      - "4000:4000"
      - "8088:8088"
    environment:
      APOLLO_ROUTER_SUPERGRAPH_PATH: /dist/supergraph.graphql
      APOLLO_ELV2_LICENSE: accept
    volumes:
      - ./apollo/admin-api/router.yaml:/dist/router.yaml:ro
      - ./apollo/admin-api/supergraph.graphql:/dist/supergraph.graphql:ro
    entrypoint:
      [
        "/bin/sh",
        "-lc",
        "while [ ! -f /dist/supergraph.graphql ]; do sleep 1; done; exec /dist/router -c /dist/router.yaml"
      ]
