$ANSIBLE_VAULT;1.1;AES256
64653361363462393138323062656664313862356130313438313536353237643234636633303864
6262383632366237336634663735396234633033373239300a626239346266343933323161333961
38613331646263323466626464643637663164663538393163373137633361616638656431323836
6537373734653765340a633661653035393039336165613136623737323338346631366636306133
35356630313664373433346437356265646333376536653061663761633933343264636562336261
39363734346432656233326465306461663965353066633438316338333539343936616666623165
32336561323231333138323632646461333035393661663535663864326461386131616664646263
63616265633835366639346331623635613961343130613936356339373733363761623136303239
32306632376136643131636331663464353462386339373037376263343835373661
