$ANSIBLE_VAULT;1.1;AES256
64353435323466623963363361636132363139336363616536396430363066633461313338333836
6466613166636461626630613865356162383838353565370a663039346463636561316437613062
37343032323366396664373863393962333565336162393962353637356432646133353436326638
6132353633333832390a393665343534326666626533616665393137616338333034376435616165
63623438656431623561356564366134663533343238613164366465356564393830666564306565
30383638393166666637386139653333323064356263333263656434353734613563326232323230
34636239396564393439366431386464343337653637653137353866646334613763333163653831
61636361616135383433333564393364613531643831393261663739336663616666653636656437
39376465383236636531373839613565353731303465323335366465316330346638
