$ANSIBLE_VAULT;1.1;AES256
36626639633535326564323430366362646336353039393664623665316130313235643039356239
6362653636616261343630386361393138613539393766370a383766396163333231653434323761
38663131396364313038383336326631643634616236333463643135343265313639633366623364
6663393164323231660a376138303431343936663134353937663632366466396566653263626331
38376464653339633561333363663338366433616537376137333330616362353063323230636262
36373439333135653738383561613737353565323533653663323066333030643164373939313036
61353066326635653439333866633538323735333534643664633537333835376263326335353965
37656661336335643961343635313565663335633265616439353736313031626236613133353163
31646664666132326231646435613839316436306534643464646437346238376538
