services:
  gitea:
    image: gitea/gitea:1.22.3-rootless
    container_name: gitea
    restart: unless-stopped
    environment:
      - GITEA__server__ROOT_URL=${GITEA_ROOT_URL:-http://localhost:3000/}
      - GITEA__server__SSH_DOMAIN=${GITEA_SSH_DOMAIN:-localhost}
      - GITEA__server__SSH_PORT=${GITEA_SSH_PORT:-2222}
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/var/lib/gitea/data/gitea.db
      - GITEA__service__DISABLE_REGISTRATION=${GITEA_DISABLE_REGISTRATION:-false}
      - GITEA__service__ALLOW_ONLY_INTERNAL_REGISTRATION=${GITEA_ALLOW_ONLY_INTERNAL_REGISTRATION:-false}
      - GITEA__service__REQUIRE_SIGNIN_VIEW=${GITEA_REQUIRE_SIGNIN_VIEW:-false}
      - GITEA__webhook__ALLOWED_HOST_LIST="external,loopback"
    ports:
      - "${GITEA_HTTP_PORT:-3000}:3000" # HTTP
      - "${GITEA_SSH_PORT:-2222}:2222" # SSH
    # Enable volumes if you want to persist data
    volumes:
      - ./data/gitea:/var/lib/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - woodpecker

networks:
  woodpecker:
    driver: bridge
