$ANSIBLE_VAULT;1.1;AES256
31306633393064343530323730393730396463393831316361336231626130336465663938366639
3065626263316635616631663538643332663135336564620a356534383163623030386435643435
66303830333335653436386436653831643466623635663565373661363037396439613335376439
3464353465383930610a653963313535353662623934333536653236613830653336636536333034
62393437663832633064313136383033303065656138353832396565306234333963393361343063
62323335353430663861643934373538366134366661303136623130343030353235656366353035
36346632343639333936396232393162616131366132646661366236643039663562303262636261
34356439393463323566626239626339666533633431333236353339313965356664623530343435
35343862313665633363666436633637316631613133366134616438623735393737303434363262
34343131643336623765643738633630326462303438393935346662626439336237646664373338
62383164323530623335353265343336303036666535356337336338623839616161313363633537
39313430666163633639623835636234306430653966303761623637306534323765343331643734
62666635303061373531356566366530323031306139373063633532373063633432316639313064
33316161363034356265373132383465653331666131633632643462383835363065613534636637
66656337356563643232313439393133663364666635386634306166303163626332623664363761
63313335653966643233353762653462643839313633376639653130363037363536303234363932
37623839666363396464613864646439333265633662643965313764373530666134643436633638
30626430613639636139653639396636313263333933643032386537366235613234336531646665
64613230353938653135353135636239626132353033313935393330343664653466616166623466
34613263383633343531363136393031323330613065636433343731363866346136653533386233
3539
