services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:next-alpine
    container_name: woodpecker-server
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
    # Enable volumes if you want to persist data
    volumes:
    - ./data/woodpecker:/var/lib/woodpecker/
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=${WOODPECKER_HOST}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_ADMIN=${WOODPECKER_ADMIN}
      - WOODPECKER_EXTENSIONS_ALLOWED_HOSTS=host.docker.internal,172.17.0.1,localhost,127.0.0.1
      # Convert (Configuration) Extension
      - WOODPECKER_CONVERT_PLUGIN_ENDPOINT=${WOODPECKER_CONVERT_PLUGIN_ENDPOINT}
      - WOODPECKER_CONVERT_PLUGIN_SECRET=${WOODPECKER_CONVERT_PLUGIN_SECRET}
      # Gitea OAuth configuration
      - WOODPECKER_GITEA=${WOODPECKER_GITEA}
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
      - WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}
      - WOODPECKER_GITEA_SKIP_VERIFY=true
    networks:
      - woodpecker
    extra_hosts:
      # This is required for oauth request to Gitea on the localhost from within a container
      - "localhost:host-gateway"
      - "host.docker.internal:host-gateway"

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3.10.0
    container_name: woodpecker-agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_MAX_WORKFLOWS=4
      - WOODPECKER_BACKEND=docker
      - WOODPECKER_BACKEND_DOCKER_NETWORK=dev_woodpecker
    networks:
      - woodpecker

networks:
  woodpecker:
    driver: bridge
